CREATE TABLE TBL_NAMES(
	NAMEID UNIQUEIDENTIFIER NOT NULL,
	FIRSTNAME NVARCHAR(50) NOT NULL,
	MIDDLENAME NVARCHAR(50) NULL,
	LASTNAME NVARCHAR(50) NOT NULL,
	STREET NVARCHAR(150) NULL,
	SUBDIVISION NVARCHAR(150) NULL,
	BARANGAY NVARCHAR(150) NULL,
	CITY NVARCHAR(150) NULL,
	PROVINCE NVARCHAR(150) NULL,
	CREATEDDATE DATETIME NOT NULL,
	CREATEDBY NVARCHAR(50) NULL,
	UPDATEDDATE DATETIME NULL,
	UPDATEDBY NVARCHAR(50) NULL,
	CONSTRAINT PK_TBL_NAMES_NAMEID PRIMARY KEY NONCLUSTERED(
		NAMEID ASC
	)ON [PRIMARY],
)ON [PRIMARY]


ALTER TABLE TBL_NAMES ADD CONSTRAINT DF_TBL_NAMES_NAMEID DEFAULT (NEWID()) FOR NAMEID
ALTER TABLE TBL_NAMES ADD CONSTRAINT DF_TBL_NAMES_CREATEDDATE DEFAULT (GETDATE()) FOR CREATEDDATE



