CREATE TABLE TBL_ADMIN (
	ADMINID UNIQUEIDENTIFIER NOT NULL,
	FIRSTNAME NVARCHAR(50) NOT NULL,
	MIDDLENAME NVARCHAR(50) NULL,
	LASTNAME NVARCHAR(50) NOT NULL,
	USERNAME NVARCHAR(50) NOT NULL,
	[PASSWORD] NVARCHAR(50) NOT NULL,
	CREATEDDATE DATETIME NOT NULL,
	CREATEDBY NVARCHAR(50) NULL,
	UPDATEDDATE DATETIME NULL,
	UPDATEDBY NVARCHAR(50) NULL,
	CONSTRAINT PK_TBL_ADMIN_ADMINID PRIMARY KEY NONCLUSTERED(
		ADMINID ASC
	)ON [PRIMARY],
	CONSTRAINT UQ_TBL_ADMIN_USERNAME_PASSWORD UNIQUE CLUSTERED(
		USERNAME ASC,
		[PASSWORD] ASC
	)ON [PRIMARY]
)ON [PRIMARY]

ALTER TABLE TBL_ADMIN ADD CONSTRAINT DF_TBL_ADMIN_ADMINID DEFAULT (NEWID()) FOR ADMINID
ALTER TABLE TBL_ADMIN ADD CONSTRAINT DF_TBL_ADMIN_CREATEDDATE DEFAULT (GETDATE()) FOR CREATEDDATE

INSERT INTO TBL_ADMIN (FIRSTNAME, MIDDLENAME, LASTNAME, USERNAME, PASSWORD)
VALUES('admin','admin','admin','admin','admin')
