//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfilingMapping.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PROFILINGMAPPINGDBEntities : DbContext
    {
        public PROFILINGMAPPINGDBEntities()
            : base("name=PROFILINGMAPPINGDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TBL_ADMIN> TBL_ADMIN { get; set; }
        public DbSet<TBL_NAMES> TBL_NAMES { get; set; }
        public DbSet<TBL_REQUEST> TBL_REQUEST { get; set; }
    }
}
