//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfilingMapping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_NAMES
    {
        public TBL_NAMES()
        {
            this.TBL_REQUEST = new HashSet<TBL_REQUEST>();
        }
    
        public System.Guid NAMEID { get; set; }
        public string FIRSTNAME { get; set; }
        public string MIDDLENAME { get; set; }
        public string LASTNAME { get; set; }
        public string STREET { get; set; }
        public string SUBDIVISION { get; set; }
        public string BARANGAY { get; set; }
        public string CITY { get; set; }
        public string PROVINCE { get; set; }
        public System.DateTime CREATEDDATE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDDATE { get; set; }
        public string UPDATEDBY { get; set; }
        public Nullable<System.DateTime> BIRTHDATE { get; set; }
        public Nullable<int> AGE { get; set; }
    
        public virtual ICollection<TBL_REQUEST> TBL_REQUEST { get; set; }
    }
}
