//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfilingMapping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_REQUEST
    {
        public System.Guid REQUESTID { get; set; }
        public System.Guid NAMEID { get; set; }
        public string COMMENT { get; set; }
        public System.DateTime CREATEDDATE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDDATE { get; set; }
        public string UPDATEDBY { get; set; }
    
        public virtual TBL_NAMES TBL_NAMES { get; set; }
    }
}
